# Generated by Django 4.1 on 2022-08-18 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomentreprise', models.CharField(db_column='NomEntreprise', max_length=45)),
                ('adressent', models.CharField(db_column='AdressEnt', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomemp', models.CharField(db_column='NomEmp', max_length=45)),
                ('preemp', models.CharField(db_column='PreEmp', max_length=45)),
                ('email', models.CharField(db_column='Email', max_length=45, unique=True)),
                ('tel', models.IntegerField(blank=True, db_column='Tel', null=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actor.entreprise')),
            ],
            options={
                'db_table': 'employes',
                'managed': True,
            },
        ),
    ]
